sudo: 'required'

language: python

python:
  - 3.6.10

services:
  - docker

install:
  - pip3 install -r requirements.txt 

jobs:
  include:
  - stage: test
    name: "Integration Tests"
    script: 
      - pytest -rA

stages:
  - test
