sudo: 'required'

language: python

python:
  - 3.6.10

addons:
  artifacts:
    s3_region: "us-west-2"
    target_paths:
      - /$TRAVIS_REPO_SLUG/

services:
  - docker

install:
  - pip3 install -r requirements.txt 

jobs:
  include:
  - stage: test
    name: "Integration Tests"
    script: 
      - pytest -rA --html=$(date +"%Y%m%d_%H%M%S")_${TRAVIS_BRANCH}_${TRAVIS_COMMIT}.html --self-contained-html

stages:
  - test
